/**
 * @file ReportGenerator.cpp
 * @brief Implementation of Professional HTML Reporting
 */
#include "../../include/core/ReportGenerator.hpp"
#include <iostream>
#include <fstream>
#include <sstream>
#include <iomanip>
#include <ctime>

// Constructor
ReportGenerator::ReportGenerator(std::string filename) : filename(filename) {}

// Add Artifact Method
void ReportGenerator::add_artifact(int id, std::string type, size_t offset, std::string hash) {
    // We add "VERIFIED" as the default status
    artifacts.push_back({id, type, offset, hash, "VERIFIED"}); 
}

// Set Stats Method
void ReportGenerator::set_stats(double duration, double throughput, int threads, size_t total, size_t encrypted) {
    stats.duration = duration;
    stats.throughput = throughput;
    stats.threads_used = threads;
    stats.total_chunks = total;
    stats.encrypted_chunks = encrypted;
}

// Helper: Get Time
std::string ReportGenerator::get_current_timestamp() {
    time_t now = time(0);
    struct tm tstruct;
    char buf[80];
    tstruct = *localtime(&now);
    strftime(buf, sizeof(buf), "%Y-%m-%d %X", &tstruct);
    return std::string(buf);
}

// Helper: Generate CSS
std::string ReportGenerator::generate_css() {
    return R"(
        <style>
            body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #121212; color: #e0e0e0; margin: 0; padding: 20px; }
            .container { max-width: 1000px; margin: 0 auto; background-color: #1e1e1e; padding: 40px; border-radius: 8px; box-shadow: 0 4px 15px rgba(0,0,0,0.5); border-top: 5px solid #00ff41; }
            h1 { color: #00ff41; border-bottom: 2px solid #333; padding-bottom: 10px; margin-top: 0; }
            h2 { color: #fff; margin-top: 30px; font-size: 1.2rem; text-transform: uppercase; letter-spacing: 1px; }
            .header-info { display: flex; justify-content: space-between; margin-bottom: 30px; color: #888; font-size: 0.9rem; }
            
            /* Metric Cards */
            .stats-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 15px; margin-bottom: 30px; }
            .card { background-color: #252526; padding: 15px; border-radius: 5px; text-align: center; border: 1px solid #333; }
            .card-value { display: block; font-size: 1.5rem; font-weight: bold; color: #00ff41; margin-bottom: 5px; }
            .card-label { font-size: 0.8rem; color: #aaa; text-transform: uppercase; }

            /* Table Styling */
            table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 0.9rem; }
            th { background-color: #2d2d2d; color: #00ff41; text-align: left; padding: 12px; border-bottom: 2px solid #00ff41; }
            td { padding: 12px; border-bottom: 1px solid #333; color: #ccc; }
            tr:hover { background-color: #2a2a2a; }
            
            /* Badges */
            .badge { padding: 4px 8px; border-radius: 4px; font-size: 0.75rem; font-weight: bold; }
            .badge-jpg { background-color: #ff4757; color: white; }
            .badge-png { background-color: #eccc68; color: black; }
            .badge-pdf { background-color: #2ed573; color: black; }
            .badge-elf { background-color: #1e90ff; color: white; }
            .hash { font-family: 'Courier New', monospace; color: #ffa502; }
            
            .footer { margin-top: 50px; text-align: center; font-size: 0.8rem; color: #555; border-top: 1px solid #333; padding-top: 20px; }
        </style>
    )";
}

// Generate Report
void ReportGenerator::generate() {
    std::ofstream file(filename);
    
    file << "<!DOCTYPE html><html><head><title>ThreadSleuth Forensic Report</title>" 
         << generate_css() << "</head><body>";
    
    file << "<div class='container'>";
    
    // --- Header ---
    file << "<div class='header-info'>";
    file << "<span>GENERATED BY: ThreadSleuth v2.0</span>";
    file << "<span>DATE: " << get_current_timestamp() << "</span>";
    file << "<span>CASE ID: TS-" << rand() % 9000 + 1000 << "</span>";
    file << "</div>";
    
    file << "<h1>DIGITAL FORENSIC ANALYSIS REPORT</h1>";
    
    // --- Executive Summary ---
    file << "<h2>EXECUTIVE SUMMARY</h2>";
    file << "<p>The forensic engine analyzed the target disk image using a parallel multi-threaded architecture. "
         << "High-entropy regions were detected, suggesting potential encryption. "
         << artifacts.size() << " artifacts were successfully carved and verified.</p>";

    // --- Statistics Grid ---
    file << "<div class='stats-grid'>";
    file << "<div class='card'><span class='card-value'>" << std::fixed << std::setprecision(2) << stats.duration << "s</span><span class='card-label'>Scan Duration</span></div>";
    file << "<div class='card'><span class='card-value'>" << std::fixed << std::setprecision(2) << stats.throughput << " MB/s</span><span class='card-label'>Disk Throughput</span></div>";
    file << "<div class='card'><span class='card-value'>" << stats.threads_used << "</span><span class='card-label'>Active Threads</span></div>";
    file << "<div class='card'><span class='card-value'>" << artifacts.size() << "</span><span class='card-label'>Artifacts Found</span></div>";
    file << "</div>";

    // --- Evidence Table ---
    file << "<h2>RECOVERED EVIDENCE CHAIN</h2>";
    if (artifacts.empty()) {
        file << "<p>No artifacts recovered.</p>";
    } else {
        file << "<table><thead><tr><th>ID</th><th>TYPE</th><th>OFFSET (HEX)</th><th>INTEGRITY HASH (SHA-256)</th><th>STATUS</th></tr></thead><tbody>";
        
        for (const auto& art : artifacts) {
            std::stringstream hex_offset;
            hex_offset << "0x" << std::hex << std::uppercase << art.offset;
            
            std::string badge_class = "badge-elf";
            if (art.type == "JPEG") badge_class = "badge-jpg";
            else if (art.type == "PNG") badge_class = "badge-png";
            else if (art.type == "PDF") badge_class = "badge-pdf";
            
            file << "<tr>"
                 << "<td>" << art.id << "</td>"
                 << "<td><span class='badge " << badge_class << "'>" << art.type << "</span></td>"
                 << "<td style='font-family: monospace;'>" << hex_offset.str() << "</td>"
                 << "<td class='hash'>" << art.hash.substr(0, 32) << "...</td>"
                 << "<td>" << art.status << "</td>"
                 << "</tr>";
        }
        file << "</tbody></table>";
    }

    // --- Footer ---
    file << "<div class='footer'>";
    file << "ThreadSleuth - Parallel & Distributed Computing Lab Project<br>";
    file << "Confidential - For Educational Use Only";
    file << "</div>";
    
    file << "</div></body></html>";
    file.close();
    
    std::cout << "[REPORT] Forensic Case File Generated: " << filename << std::endl;
}
